### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by ndkean** [systemofapwne/leetmouse#24]
Command: 
`sudo dkms install -m leetmouse-driver -v 0.9.0`
Console output:
```
Sign command: /lib/modules/6.0.12-300.fc37.x86_64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Certificate or key are missing, generating self signed certificate for MOK...

Building module:
Cleaning build area...
KERNELDIR=/lib/modules/6.0.12-300.fc37.x86_64/build make driver udev_trigger...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.0.12-300.fc37.x86_64 (x86_64)
Consult /var/lib/dkms/leetmouse-driver/0.9.0/build/make.log for more information.
```
/var/lib/dkms/leetmouse-driver/0.9.0/build/make.log:
```
DKMS make.log for leetmouse-driver-0.9.0 for kernel 6.0.12-300.fc37.x86_64 (x86_64)

Wed Dec 14 01:02:18 AM CST 2022

::[32m Compiling leetmouse kernel module[0m
========================================
cp -n /var/lib/dkms/leetmouse-driver/0.9.0/build/driver/config.sample.h /var/lib/dkms/leetmouse-driver/0.9.0/build/driver/config.h
make -C /lib/modules/6.0.12-300.fc37.x86_64/build M=/var/lib/dkms/leetmouse-driver/0.9.0/build/driver modules
make[1]: Entering directory '/usr/src/kernels/6.0.12-300.fc37.x86_64'
  CC [M]  /var/lib/dkms/leetmouse-driver/0.9.0/build/driver/usbmouse.o
/var/lib/dkms/leetmouse-driver/0.9.0/build/driver/usbmouse.c: In function ‘usb_mouse_probe’:
/var/lib/dkms/leetmouse-driver/0.9.0/build/driver/usbmouse.c:183:12: error: too many arguments to function ‘usb_maxpacket’
  183 |     maxp = usb_maxpacket(dev, pipe, usb_pipeout(pipe));
      |            ^~~~~~~~~~~~~
In file included from ./include/linux/usb/input.h:9,
                 from /var/lib/dkms/leetmouse-driver/0.9.0/build/driver/usbmouse.c:25:
./include/linux/usb.h:1976:19: note: declared here
 1976 | static inline u16 usb_maxpacket(struct usb_device *udev, int pipe)
      |                   ^~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:249: /var/lib/dkms/leetmouse-driver/0.9.0/build/driver/usbmouse.o] Error 1
make[1]: *** [Makefile:1856: /var/lib/dkms/leetmouse-driver/0.9.0/build/driver] Error 2
make[1]: Leaving directory '/usr/src/kernels/6.0.12-300.fc37.x86_64'
make: *** [Makefile:26: driver] Error 2`
```

**Comment by systemofapwne** [comment]
I thougt, that I already fixed that with this commit: https://github.com/systemofapwne/leetmouse/commit/d3cc91c86d22f9fe17bb79cefaa458662a228ee9

Please remove all remnants of leetmouse from your system, clone/pull latest changes from the repo and try again.

**Comment by ndkean** [comment]
Worked, thanks.
